import type { Locale } from "./i18n";
import type { ClassKey } from "./data";

/** Textos del sitio en cada idioma. Los datos estructurales (precios, horarios, imágenes) siguen en `lib/data.ts`. */
const es = {
  siteTagline: "Ballet, barre, salsa, tango y yoga",
  description: "Estudio boutique de ballet & barre con más de 40 años de historia. Reserva tus clases de baby ballet, ballet infantil, junior, salsa, tango y yoga.",
  ogDescription: "El arte de moverse con gracia.",
  ogLocale: "es_CO",
  whatsappMessage: "Hola quiero mas información sobre Relevé Ballet Studio.",

  ui: {
    language: "Idioma",
    nav: { "/": "Inicio", "/servicios": "Servicios", "/reservar-clase": "Reservar clase", "/tienda": "Tienda" } as Record<string, string>,
    navMain: "Principal",
    openMenu: "Abrir menú",
    closeMenu: "Cerrar menú",
    mobileMenu: "Menú móvil",
    quickLinks: "Accesos rápidos",
    whatsappAria: "Escribir por WhatsApp",
    scrollAria: "Desplazarse",
  },

  footer: {
    desc: "Estudio boutique de ballet & barre.",
    navAria: "Navegación de pie de página",
    explore: "Explorar",
    studio: "El estudio",
    programs: "Programas",
    services: "Servicios",
    book: "Reservar clase",
    shop: "Tienda",
    contact: "Contacto",
    whatsapp: "Escríbenos por WhatsApp",
    cta: "Reservar una clase",
    rights: "Todos los derechos reservados.",
  },

  contact: {
    kicker: "Contáctanos",
    title: "Hablemos de tu\npróxima clase o evento.",
    lead: "Cuéntanos qué necesitas —clases, una coreografía o una clase para tu empresa— y te respondemos pronto.",
    whatsapp: "Escribir por WhatsApp",
    name: "Nombre",
    email: "Correo",
    phone: "Teléfono / WhatsApp",
    message: "Mensaje",
    placeholder: "Cuéntanos qué necesitas…",
    send: "Enviar mensaje",
    sending: "Enviando…",
    ok: "¡Gracias! Recibimos tu mensaje y te responderemos pronto.",
    error: "No pudimos enviar tu mensaje.",
  },

  hero: {
    eyebrow: "Estudio boutique de ballet & barre",
    title: "El arte de moverse con gracia.",
    lead: "Técnica, disciplina y sensibilidad artística: desde los primeros pasos hasta la excelencia en punta.",
    book: "Reservar una clase",
    programs: "Ver programas",
    imgAlt: "Niñas bailando ballet en el estudio Relevé",
    caption1: "Más de 40 años formando bailarinas.",
    caption2: "Baby ballet · Infantil · Junior · Salsa · Tango · Yoga.",
    card1: "Reservar clases",
    card1Sub: "Calendario en línea",
    card2: "La tienda",
    card2Sub: "Kit de bailarina",
  },

  intro: {
    kicker: "Sobre Relevé",
    title: ["Un estudio pensado", "para el arte de la danza."],
    p1: "Relevé nace como un espacio dedicado al ballet clásico y al trabajo de barre, donde la técnica se enseña con calidez y precisión. Cada clase está diseñada para acompañar el crecimiento de cada bailarina —cuerpo, disciplina y expresión— en un ambiente cuidado hasta el último detalle.",
    p2: "Creemos que el ballet es, ante todo, una forma de encontrarse a una misma: postura, respiración, música y movimiento en un mismo instante.",
    imgAlt: "Clase de ballet infantil en el estudio",
  },

  stats: {
    kicker: "Nuestra historia",
    captions: ["Años de ser fundada", "Alumnas que han formado parte de nuestra historia", "Clases impartidas", "Presentaciones y shows realizados en Colombia"],
  },

  programsSection: {
    kicker: "Nuestros programas",
    title: "Clases pensadas para cada etapa.",
    adults: "Para jóvenes y adultos +13",
    adultLabels: { yoga: "Yoga", salsa: "Salsa", tango: "Tango" } as Record<string, string>,
    adultAlt: (label: string) => `Clase de ${label.toLowerCase()}`,
    programs: [
      { title: "Baby Ballet", body: "Primeros pasos en el mundo del ballet para niñas menores de 7 años, acompañadas por sus padres. Movimiento, música y juego para despertar el amor por la danza.", cta: "Reservar clase" },
      { title: "Ballet Clásico", body: "Formación técnica progresiva en Infantil 1, Infantil 2 y Junior: posiciones, alineación, musicalidad y expresión artística en cada nivel.", cta: "Reservar clase" },
      { title: "Barre & Técnica", body: "Trabajo en barra que fortalece, alinea y perfecciona cada movimiento — la base de una técnica sólida y una postura elegante.", cta: "Reservar clase" },
      { title: "Yoga", body: "Clase para jóvenes y adultos desde los 13 años. Flexibilidad, respiración y fuerza consciente en un espacio sereno, ideal para complementar el ballet o empezar de cero.", cta: "Reservar clase" },
      { title: "Salsa", body: "Para jóvenes y adultos desde los 13 años, sin experiencia previa. Ritmo, coordinación y mucha energía: aprende pasos, giros y baile en pareja en un ambiente divertido.", cta: "Reservar clase" },
      { title: "Tango", body: "Para jóvenes y adultos desde los 13 años. Abrazo, postura, caminata y musicalidad: la elegancia del tango paso a paso, con o sin pareja.", cta: "Reservar clase" },
    ],
  },

  experience: {
    kicker: "La experiencia Relevé",
    title: "Detalles que hacen la diferencia.",
    items: [
      { title: "Técnica", body: "Formación progresiva y estructurada, con atención personalizada en cada clase." },
      { title: "Comunidad", body: "Un ambiente cálido donde cada bailarina se siente acompañada, dentro y fuera de la barra." },
      { title: "Disciplina", body: "Hábitos de constancia, postura y compromiso que trascienden el estudio." },
      { title: "Elegancia", body: "Una experiencia cuidada en cada detalle: del espacio a cada movimiento." },
    ],
  },

  marquee: ["Baby Ballet", "Ballet Infantil", "Ballet Junior", "Salsa", "Tango", "Yoga", "Barre"],

  teaser: {
    kicker: "Servicios especiales",
    title: "Para tus momentos más importantes.",
    short: {
      quinceaneras: "Creamos y ensayamos la coreografía de tus 15: vals, sorpresa o show, diseñada a tu estilo y con acompañamiento hasta el gran día.",
      matrimonios: "Tu primer baile, como lo soñaste: coreografías para novios y familiares, adaptadas a tu música y a tu nivel, sin necesidad de experiencia.",
    } as Record<string, string>,
    corpIntro: "Bienestar, integración y buen ambiente para tu equipo. Tú eliges la modalidad:",
    corp1: ["Vamos a tu empresa.", "Llevamos la clase de salsa o yoga a tu oficina o evento."],
    corp2: ["Tu empresa viene al estudio.", "Tu equipo disfruta la clase en nuestro espacio."],
    more: "Ver más",
    all: "Ver todos los servicios",
  },

  services: {
    meta: { title: "Servicios", description: "Coreografías para quinceañeras y matrimonios, y clases empresariales de salsa y yoga." },
    kicker: "Más que clases",
    title: "Servicios",
    lead: "Coreografías para tus fechas más especiales y clases de bienestar para tu empresa.",
    quote: "Cotizar ahora",
    see: "Ver servicios",
    request: "Solicitar cotización",
    stepsKicker: "Cómo trabajamos",
    stepsTitle: "Del primer mensaje al gran día.",
    contactTitle: "Cuéntanos qué\ntienes en mente.",
    contactLead: "Escríbenos y te respondemos con una propuesta personalizada.",
    contactWa: "Hola, quiero información sobre sus servicios.",
    steps: [
      { title: "Cuéntanos", body: "Fecha, tipo de evento, música e ideas que tengas." },
      { title: "Cotizamos", body: "Te enviamos una propuesta clara, a tu medida." },
      { title: "Creamos", body: "Diseñamos la coreografía o la clase y la ensayamos contigo." },
      { title: "Disfruta", body: "Brillas en tu evento, o tu equipo vive una gran experiencia." },
    ],
    items: {
      quinceaneras: {
        kicker: "Quince años",
        title: "Coreografía para quinceañeras",
        text: "El vals y el baile sorpresa son el corazón de tu fiesta. Diseñamos una coreografía a tu medida —con tu música, tu estilo y tu corte— y la ensayamos contigo hasta que te sientas segura y radiante.",
        items: ["Vals, baile sorpresa o show a tu gusto", "Montaje para la quinceañera, la corte y familiares", "Ensayos en el estudio, en grupo o individuales", "Acompañamiento hasta el día del evento"],
        msg: "Hola, quiero cotizar una coreografía para unos quince años.",
      },
      matrimonios: {
        kicker: "Matrimonios",
        title: "Coreografía para matrimonios",
        text: "Tu primer baile, como lo soñaste. Creamos una coreografía elegante y natural para los novios, sin necesidad de experiencia, y también para padres, padrinos y cortejo si quieres sorprender.",
        items: ["Primer baile de novios personalizado", "Coreografías para padres, familiares o cortejo", "Adaptada a tu canción y a tu nivel", "Ensayos con horarios flexibles"],
        msg: "Hola, quiero cotizar una coreografía para un matrimonio.",
      },
      empresariales: {
        kicker: "Empresas",
        title: "Clases empresariales de salsa y yoga",
        text: "Bienestar, integración y buen ambiente para tu equipo. Clases de salsa o yoga para cualquier nivel, con dos modalidades para que elijas la que mejor se adapte a tu empresa.",
        items: ["Vamos a tu empresa: llevamos la clase a tu oficina o evento", "Tu empresa viene al estudio: tu equipo disfruta nuestro espacio", "Salsa o yoga, para grupos pequeños y grandes", "Ideal para pausas activas, integraciones y celebraciones"],
        msg: "Hola, quiero cotizar una clase empresarial (salsa o yoga) para mi empresa.",
      },
    } as Record<string, { kicker: string; title: string; text: string; items: string[]; msg: string }>,
  },

  shop: {
    meta: { title: "Tienda", description: "Vestuario, calzado y accesorios de ballet seleccionados con el mismo cuidado que ponemos en cada clase." },
    kicker: "Tienda Relevé",
    title: "Lo esencial para cada bailarina.",
    lead: "Vestuario, calzado y accesorios seleccionados con el mismo cuidado que ponemos en cada clase.",
    order: "Pedir por WhatsApp",
    waMessage: (name: string) => `Hola, quiero información sobre: ${name}.`,
    products: {
      zapatillas: { name: "Zapatillas", blurb: "Media punta y punta para cada nivel." },
      mallas: { name: "Mallas", blurb: "Cómodas, elásticas y con caída elegante." },
      faldas: { name: "Faldas", blurb: "Tul y gasa para dar vuelo a cada movimiento." },
      medias: { name: "Medias", blurb: "Medias de ballet suaves y resistentes." },
      "accesorios-para-el-cabello": { name: "Accesorios para el cabello", blurb: "Moños, cintas y redes para el peinado perfecto." },
    } as Record<string, { name: string; blurb: string }>,
  },

  booking: {
    meta: { title: "Reservar clase", description: "Reserva tu clase de baby ballet, ballet infantil, junior, salsa, tango o yoga desde el calendario." },
    kicker: "Agenda tu lugar",
    title: "Reservar clase",
    lead: "Elige tu plan, escoge los días en el calendario y listo. Clases de 1 hora, con cupos limitados.",
    step1: "Elige tu plan",
    planAria: "Plan",
    single: "Clase individual",
    singleNote: "por clase · elige las que quieras",
    monthly: "Mes ilimitado",
    monthlyNote: "clases ilimitadas durante 30 días",
    bestValue: "Mejor valor",
    step2: "Escoge fecha y clase",
    prevWeek: "Semana anterior",
    nextWeek: "Semana siguiente",
    daysAria: "Días de la semana",
    dayShort: ["Lun", "Mar", "Mié", "Jue", "Vie", "Sáb"],
    dayLong: ["lunes", "martes", "miércoles", "jueves", "viernes", "sábado", "domingo"],
    months: ["enero", "febrero", "marzo", "abril", "mayo", "junio", "julio", "agosto", "septiembre", "octubre", "noviembre", "diciembre"],
    hours: "Lunes a viernes 3:00 pm – 8:00 pm · Sábados 7:00 am – 3:00 pm",
    noClasses: "No hay clases este día.",
    picked: "✓ Elegida",
    closed: "Cerrada",
    full: "Completa",
    fewLeft: (n: number) => `¡Quedan ${n}!`,
    spots: (n: number) => `${n} cupos`,
    step3: "Tus datos",
    none: "Aún no has elegido clases.",
    remove: "Quitar",
    total: "Total",
    unlimited: " · mes ilimitado",
    fullName: "Nombre completo",
    email: "Correo",
    phone: "Teléfono / WhatsApp",
    confirm: "Confirmar reserva",
    booking: "Reservando…",
    fine: "Te contactaremos por WhatsApp o correo para confirmar y coordinar el pago.",
    errFail: "No pudimos completar la reserva.",
    errOffline: "Sin conexión. Inténtalo de nuevo.",
    doneTitle: "¡Reserva recibida!",
    doneText: (name: string, ref: string, count: number, total: string) => `Gracias, ${name}. Tu referencia es ${ref} (${count} ${count === 1 ? "clase" : "clases"} · ${total}).`,
    doneWa: "Confirmar por WhatsApp",
    doneWaMsg: (ref: string) => `Hola, hice la reserva ${ref} en Relevé. Quiero confirmar y coordinar el pago.`,
    again: "Hacer otra reserva",
    classes: {
      baby: { label: "Baby Ballet", desc: "Menores de 7 años, con acompañante" },
      infantil1: { label: "Ballet Infantil 1", desc: "Iniciación técnica · 7 a 9 años" },
      infantil2: { label: "Ballet Infantil 2", desc: "Técnica intermedia · 9 a 11 años" },
      junior: { label: "Ballet Junior", desc: "Técnica avanzada · desde 12 años" },
      salsa: { label: "Salsa", desc: "Ritmo y coordinación · desde 13 años" },
      tango: { label: "Tango", desc: "Abrazo, postura y musicalidad" },
      yoga: { label: "Yoga", desc: "Flexibilidad, respiración y calma" },
    } as Record<ClassKey, { label: string; desc: string }>,
  },
};

export type Content = typeof es;

const en: Content = {
  siteTagline: "Ballet, barre, salsa, tango and yoga",
  description: "A boutique ballet & barre studio with over 40 years of history. Book your baby ballet, kids' ballet, junior, salsa, tango and yoga classes.",
  ogDescription: "The art of moving with grace.",
  ogLocale: "en_US",
  whatsappMessage: "Hi, I'd like more information about Relevé Ballet Studio.",

  ui: {
    language: "Language",
    nav: { "/": "Home", "/servicios": "Services", "/reservar-clase": "Book a class", "/tienda": "Shop" },
    navMain: "Main",
    openMenu: "Open menu",
    closeMenu: "Close menu",
    mobileMenu: "Mobile menu",
    quickLinks: "Quick links",
    whatsappAria: "Message us on WhatsApp",
    scrollAria: "Scroll down",
  },

  footer: {
    desc: "A boutique ballet & barre studio.",
    navAria: "Footer navigation",
    explore: "Explore",
    studio: "The studio",
    programs: "Programs",
    services: "Services",
    book: "Book a class",
    shop: "Shop",
    contact: "Contact",
    whatsapp: "Message us on WhatsApp",
    cta: "Book a class",
    rights: "All rights reserved.",
  },

  contact: {
    kicker: "Contact us",
    title: "Let's talk about your\nnext class or event.",
    lead: "Tell us what you need — classes, a choreography or a class for your company — and we'll get back to you soon.",
    whatsapp: "Message us on WhatsApp",
    name: "Name",
    email: "Email",
    phone: "Phone / WhatsApp",
    message: "Message",
    placeholder: "Tell us what you need…",
    send: "Send message",
    sending: "Sending…",
    ok: "Thank you! We received your message and will reply soon.",
    error: "We couldn't send your message.",
  },

  hero: {
    eyebrow: "Boutique ballet & barre studio",
    title: "The art of moving with grace.",
    lead: "Technique, discipline and artistic sensitivity: from the very first steps to excellence en pointe.",
    book: "Book a class",
    programs: "See programs",
    imgAlt: "Girls dancing ballet at the Relevé studio",
    caption1: "Over 40 years training dancers.",
    caption2: "Baby ballet · Kids · Junior · Salsa · Tango · Yoga.",
    card1: "Book classes",
    card1Sub: "Online calendar",
    card2: "The shop",
    card2Sub: "Dancer's kit",
  },

  intro: {
    kicker: "About Relevé",
    title: ["A studio designed", "for the art of dance."],
    p1: "Relevé was born as a space devoted to classical ballet and barre work, where technique is taught with warmth and precision. Every class is designed to support each dancer's growth — body, discipline and expression — in an environment cared for down to the last detail.",
    p2: "We believe ballet is, above all, a way of finding oneself: posture, breath, music and movement in a single instant.",
    imgAlt: "Kids' ballet class at the studio",
  },

  stats: {
    kicker: "Our story",
    captions: ["Years since our founding", "Students who have been part of our story", "Classes taught", "Performances and shows across Colombia"],
  },

  programsSection: {
    kicker: "Our programs",
    title: "Classes designed for every stage.",
    adults: "For teens and adults 13+",
    adultLabels: { yoga: "Yoga", salsa: "Salsa", tango: "Tango" },
    adultAlt: (label: string) => `${label} class`,
    programs: [
      { title: "Baby Ballet", body: "First steps into the world of ballet for girls under 7, accompanied by their parents. Movement, music and play to awaken a love for dance.", cta: "Book a class" },
      { title: "Classical Ballet", body: "Progressive technical training in Kids 1, Kids 2 and Junior: positions, alignment, musicality and artistic expression at every level.", cta: "Book a class" },
      { title: "Barre & Technique", body: "Barre work that strengthens, aligns and refines every movement — the foundation of solid technique and elegant posture.", cta: "Book a class" },
      { title: "Yoga", body: "A class for teens and adults from age 13. Flexibility, breathing and mindful strength in a serene space, ideal to complement ballet or to start from scratch.", cta: "Book a class" },
      { title: "Salsa", body: "For teens and adults from age 13, no prior experience needed. Rhythm, coordination and lots of energy: learn steps, turns and partner dancing in a fun atmosphere.", cta: "Book a class" },
      { title: "Tango", body: "For teens and adults from age 13. Embrace, posture, walk and musicality: the elegance of tango step by step, with or without a partner.", cta: "Book a class" },
    ],
  },

  experience: {
    kicker: "The Relevé experience",
    title: "Details that make the difference.",
    items: [
      { title: "Technique", body: "Progressive, structured training with personal attention in every class." },
      { title: "Community", body: "A warm environment where every dancer feels supported, at the barre and beyond." },
      { title: "Discipline", body: "Habits of consistency, posture and commitment that reach beyond the studio." },
      { title: "Elegance", body: "An experience cared for in every detail: from the space to every movement." },
    ],
  },

  marquee: ["Baby Ballet", "Kids' Ballet", "Junior Ballet", "Salsa", "Tango", "Yoga", "Barre"],

  teaser: {
    kicker: "Special services",
    title: "For your most important moments.",
    short: {
      quinceaneras: "We create and rehearse your quinceañera choreography: waltz, surprise dance or show, designed to your style and with support until the big day.",
      matrimonios: "Your first dance, just as you dreamed it: choreographies for couples and family, adapted to your music and level, no experience needed.",
    },
    corpIntro: "Wellness, team bonding and a great atmosphere for your team. You choose the format:",
    corp1: ["We come to your company.", "We bring the salsa or yoga class to your office or event."],
    corp2: ["Your company comes to the studio.", "Your team enjoys the class in our space."],
    more: "Learn more",
    all: "See all services",
  },

  services: {
    meta: { title: "Services", description: "Choreographies for quinceañeras and weddings, and corporate salsa and yoga classes." },
    kicker: "More than classes",
    title: "Services",
    lead: "Choreographies for your most special dates and wellness classes for your company.",
    quote: "Get a quote",
    see: "See services",
    request: "Request a quote",
    stepsKicker: "How we work",
    stepsTitle: "From the first message to the big day.",
    contactTitle: "Tell us what\nyou have in mind.",
    contactLead: "Write to us and we'll reply with a personalized proposal.",
    contactWa: "Hi, I'd like information about your services.",
    steps: [
      { title: "Tell us", body: "Date, type of event, music and any ideas you have." },
      { title: "We quote", body: "We send you a clear proposal, tailored to you." },
      { title: "We create", body: "We design the choreography or class and rehearse it with you." },
      { title: "Enjoy", body: "You shine at your event, or your team has a great experience." },
    ],
    items: {
      quinceaneras: {
        kicker: "Quinceañeras",
        title: "Quinceañera choreography",
        text: "The waltz and the surprise dance are the heart of your party. We design a choreography made for you — with your music, your style and your court — and rehearse it with you until you feel confident and radiant.",
        items: ["Waltz, surprise dance or show, as you like", "Choreography for the quinceañera, her court and family", "Rehearsals at the studio, in groups or one-on-one", "Support all the way to the day of the event"],
        msg: "Hi, I'd like a quote for a quinceañera choreography.",
      },
      matrimonios: {
        kicker: "Weddings",
        title: "Wedding choreography",
        text: "Your first dance, just as you dreamed it. We create an elegant, natural choreography for the couple, no experience needed, and also for parents, godparents and wedding party if you want to surprise.",
        items: ["Personalized first dance for the couple", "Choreographies for parents, family or wedding party", "Adapted to your song and your level", "Rehearsals with flexible schedules"],
        msg: "Hi, I'd like a quote for a wedding choreography.",
      },
      empresariales: {
        kicker: "Corporate",
        title: "Corporate salsa and yoga classes",
        text: "Wellness, team bonding and a great atmosphere for your team. Salsa or yoga classes for any level, with two formats so you can choose the one that suits your company best.",
        items: ["We come to your company: we bring the class to your office or event", "Your company comes to the studio: your team enjoys our space", "Salsa or yoga, for small and large groups", "Ideal for active breaks, team events and celebrations"],
        msg: "Hi, I'd like a quote for a corporate class (salsa or yoga) for my company.",
      },
    },
  },

  shop: {
    meta: { title: "Shop", description: "Ballet apparel, footwear and accessories selected with the same care we put into every class." },
    kicker: "Relevé Shop",
    title: "The essentials for every dancer.",
    lead: "Apparel, footwear and accessories selected with the same care we put into every class.",
    order: "Order via WhatsApp",
    waMessage: (name: string) => `Hi, I'd like information about: ${name}.`,
    products: {
      zapatillas: { name: "Ballet shoes", blurb: "Demi-pointe and pointe for every level." },
      mallas: { name: "Leotards", blurb: "Comfortable, stretchy, with an elegant drape." },
      faldas: { name: "Skirts", blurb: "Tulle and chiffon to give every movement flow." },
      medias: { name: "Tights", blurb: "Soft, durable ballet tights." },
      "accesorios-para-el-cabello": { name: "Hair accessories", blurb: "Buns, ribbons and nets for the perfect hairstyle." },
    },
  },

  booking: {
    meta: { title: "Book a class", description: "Book your baby ballet, kids' ballet, junior, salsa, tango or yoga class from the calendar." },
    kicker: "Reserve your spot",
    title: "Book a class",
    lead: "Choose your plan, pick your days on the calendar and you're done. 1-hour classes with limited spots.",
    step1: "Choose your plan",
    planAria: "Plan",
    single: "Single class",
    singleNote: "per class · pick as many as you like",
    monthly: "Unlimited month",
    monthlyNote: "unlimited classes for 30 days",
    bestValue: "Best value",
    step2: "Pick a date and class",
    prevWeek: "Previous week",
    nextWeek: "Next week",
    daysAria: "Days of the week",
    dayShort: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
    dayLong: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
    months: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
    hours: "Monday to Friday 3:00 pm – 8:00 pm · Saturdays 7:00 am – 3:00 pm",
    noClasses: "No classes this day.",
    picked: "✓ Selected",
    closed: "Closed",
    full: "Full",
    fewLeft: (n: number) => `Only ${n} left!`,
    spots: (n: number) => `${n} spots`,
    step3: "Your details",
    none: "You haven't picked any classes yet.",
    remove: "Remove",
    total: "Total",
    unlimited: " · unlimited month",
    fullName: "Full name",
    email: "Email",
    phone: "Phone / WhatsApp",
    confirm: "Confirm booking",
    booking: "Booking…",
    fine: "We'll contact you via WhatsApp or email to confirm and arrange payment.",
    errFail: "We couldn't complete your booking.",
    errOffline: "No connection. Please try again.",
    doneTitle: "Booking received!",
    doneText: (name: string, ref: string, count: number, total: string) => `Thank you, ${name}. Your reference is ${ref} (${count} ${count === 1 ? "class" : "classes"} · ${total}).`,
    doneWa: "Confirm via WhatsApp",
    doneWaMsg: (ref: string) => `Hi, I made booking ${ref} at Relevé. I'd like to confirm and arrange payment.`,
    again: "Make another booking",
    classes: {
      baby: { label: "Baby Ballet", desc: "Under 7, with a companion" },
      infantil1: { label: "Kids' Ballet 1", desc: "Technical introduction · ages 7–9" },
      infantil2: { label: "Kids' Ballet 2", desc: "Intermediate technique · ages 9–11" },
      junior: { label: "Junior Ballet", desc: "Advanced technique · from age 12" },
      salsa: { label: "Salsa", desc: "Rhythm and coordination · from age 13" },
      tango: { label: "Tango", desc: "Embrace, posture and musicality" },
      yoga: { label: "Yoga", desc: "Flexibility, breathing and calm" },
    },
  },
};

const DICTS: Record<Locale, Content> = { es, en };

export const getContent = (locale: Locale): Content => DICTS[locale];
